  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ivan-frontend
    restart: unless-stopped
    ports:
      - "3000:80"   # serve production build on port 3000
    networks:
      - ivan-network
    depends_on:
      backend:
        condition: service_started
    command: ["nginx", "-g", "daemon off;"] # keep nginx running
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html:ro # serve static files from build
      - /etc/nginx/conf.d # keep default conf to avoid nginx errors
      - /var/cache/nginx # keep cache dir to avoid nginx errors
      - /var/log/nginx # keep log dir to avoid nginx errors
      - /usr/share/nginx/html # keep html dir to avoid nginx errors
      - /usr/share/nginx/modules # keep modules dir to avoid nginx errors
      - /etc/nginx/modules # keep modules dir to avoid nginx errors
      - /etc/nginx/ssl # keep ssl dir to avoid nginx errors
      - /etc/nginx/snippets # keep snippets dir to avoid nginx errors
      - /etc/nginx/sites-available # keep sites-available dir to avoid nginx errors
      - /etc/nginx/sites-enabled # keep sites-enabled dir to avoid nginx errors
      - /etc/nginx/mime.types # keep mime.types file to avoid nginx errors
      - /etc/nginx/fastcgi_params # keep fastcgi_params file to avoid nginx errors
      - /etc/nginx/koi-utf # keep koi-utf file to avoid nginx errors
      - /etc/nginx/koi-win # keep koi-win file to avoid nginx errors
      - /etc/nginx/scgi_params # keep scgi_params file to avoid nginx errors
      - /etc/nginx/uwsgi_params # keep uwsgi_params file to avoid nginx errors
      - /etc/nginx/proxy_params # keep proxy_params file to avoid nginx errors
      - /etc/nginx/conf.d/default.conf # keep default conf to avoid nginx errors
      - /etc/nginx/nginx.conf # keep nginx.conf to avoid nginx errors