version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: ivan-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ivan_dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - ivan-network

  redis:
    image: redis:7-alpine
    container_name: ivan-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ivan-network

  minio:
    image: minio/minio:latest
    container_name: ivan-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ivan-network

networks:
  ivan-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  minio_data: