# infrastructure/kubernetes/services/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ivanchat-backend
  namespace: ivanchat
  labels:
    app: ivanchat-backend
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    port: 5000
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 5001
    targetPort: websocket
    protocol: TCP
  selector:
    app: ivanchat-backend
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: ivanchat-backend-headless
  namespace: ivanchat
  labels:
    app: ivanchat-backend
    component: backend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 5000
    targetPort: http
  - name: websocket
    port: 5001
    targetPort: websocket
  selector:
    app: ivanchat-backend
    component: backend